### ISSUE TITLE
Fails to compile on vxWorks 6.9.4.1

### ISSUE THREAD

**Issue by MarkRivers** [epics-modules/script#15]
I get an error trying to compile lua master branch on vxWorks 6.9.4.1

```
/usr/local/vw/vxWorks-6.9.4/gnu/4.3.3-vxworks-6.9/x86-linux2/bin/ccppc           -DUSE_TYPED_RSET  -DCPU=PPC32  -DvxWorks=vxWorks -include /usr/local/vw/vxWorks-6.9.4/vxworks-6.9/target/h/vxWorks.h    -O2   -Wall      -mstrict-align -mlongcall    -fno-builtin  -I. -I../O.Common -I. -I. -I.. -I../../../luaApp/src/core -I../../../luaApp/src/devSupport -I../../../luaApp/src/rec -I../../../luaApp/src/shell -I../../../luaApp/src/libs -I../../../include/compiler/gcc -I../../../include/os/vxWorks -I../../../include   -I/corvette/home/epics/devel/include   -I/corvette/home/epics/devel/asyn-4-37/include -I/corvette/usr/local/epics-devel/base-7.0.3.1/include/compiler/gcc -I/corvette/usr/local/epics-devel/base-7.0.3.1/include/os/vxWorks -I/corvette/usr/local/epics-devel/base-7.0.3.1/include       -I/usr/local/vw/vxWorks-6.9.4/vxworks-6.9/target/h -I/usr/local/vw/vxWorks-6.9.4/vxworks-6.9/target/h/wrn/coreip -c ../../../luaApp/src/rec/luascriptRecord.cpp
../../../luaApp/src/rec/luascriptRecord.cpp: In function 'int createTable(lua_State*, DBLINK*, short int, long int*, bool) [with T = unsigned char]':
../../../luaApp/src/rec/luascriptRecord.cpp:354:   instantiated from here
../../../luaApp/src/rec/luascriptRecord.cpp:295: error: 'class std::vector<unsigned char, std::allocator<unsigned char> >' has no member named 'data'
../../../luaApp/src/rec/luascriptRecord.cpp: In function 'int createTable(lua_State*, DBLINK*, short int, long int*, bool) [with T = short int]':
../../../luaApp/src/rec/luascriptRecord.cpp:358:   instantiated from here
../../../luaApp/src/rec/luascriptRecord.cpp:295: error: 'class std::vector<short int, std::allocator<short int> >' has no member named 'data'
../../../luaApp/src/rec/luascriptRecord.cpp: In function 'int createTable(lua_State*, DBLINK*, short int, long int*, bool) [with T = short unsigned int]':
../../../luaApp/src/rec/luascriptRecord.cpp:362:   instantiated from here
../../../luaApp/src/rec/luascriptRecord.cpp:295: error: 'class std::vector<short unsigned int, std::allocator<short unsigned int> >' has no member named 'data'
../../../luaApp/src/rec/luascriptRecord.cpp: In function 'int createTable(lua_State*, DBLINK*, short int, long int*, bool) [with T = int]':
../../../luaApp/src/rec/luascriptRecord.cpp:366:   instantiated from here
../../../luaApp/src/rec/luascriptRecord.cpp:295: error: 'class std::vector<int, std::allocator<int> >' has no member named 'data'
../../../luaApp/src/rec/luascriptRecord.cpp: In function 'int createTable(lua_State*, DBLINK*, short int, long int*, bool) [with T = unsigned int]':
../../../luaApp/src/rec/luascriptRecord.cpp:370:   instantiated from here
../../../luaApp/src/rec/luascriptRecord.cpp:295: error: 'class std::vector<unsigned int, std::allocator<unsigned int> >' has no member named 'data'
../../../luaApp/src/rec/luascriptRecord.cpp: In function 'int createTable(lua_State*, DBLINK*, short int, long int*, bool) [with T = float]':
../../../luaApp/src/rec/luascriptRecord.cpp:374:   instantiated from here
../../../luaApp/src/rec/luascriptRecord.cpp:295: error: 'class std::vector<float, std::allocator<float> >' has no member named 'data'
../../../luaApp/src/rec/luascriptRecord.cpp: In function 'int createTable(lua_State*, DBLINK*, short int, long int*, bool) [with T = double]':
../../../luaApp/src/rec/luascriptRecord.cpp:378:   instantiated from here
../../../luaApp/src/rec/luascriptRecord.cpp:295: error: 'class std::vector<double, std::allocator<double> >' has no member named 'data'
make[3]: *** [luascriptRecord.o] Error 1
make[3]: Leaving directory `/home/epics/devel/lua-2-1/luaApp/src/O.vxWorks-ppc32'
make[2]: *** [install.vxWorks-ppc32] Error 2
make[2]: Leaving directory `/home/epics/devel/lua-2-1/luaApp/src'
make[1]: *** [src.install] Error 2
make[1]: Leaving directory `/home/epics/devel/lua-2-1/luaApp'
make: *** [luaApp.install] Error 2
```

**Comment by keenanlang** [comment]
std::vector::data was introduced in C++11, but I forgot. Fixed.
